#Kubernetes 1.7+
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: zk-pdb
  labels:
    app: zookeeper
spec:
  selector:
    matchLabels:
      app: zookeeper
  maxUnavailable: 1