---
apiVersion: v1
kind: Service
metadata:
  name: nacos-mysql
  namespace: nacos
  labels:
    name: nacos-mysql
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    name: nacos-mysql
  clusterIP: None