---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nacos-mysql-data
  namespace: nacos
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
  volumeMode: Filesystem
