apiVersion: v1
kind: ReplicationController
metadata:
  name: nacos-mysql
  namespace: nacos
  labels:
    name: nacos-mysql
spec:
  replicas: 1
  selector:
    name: nacos-mysql
  template:
    metadata:
      labels:
        name: nacos-mysql
    spec:
      containers:
      - name: nacos-mysql
        image: nacos/nacos-mysql:5.7
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
        - name: MYSQL_DATABASE
          value: "nacos_db"
        - name: MYSQL_USER
          value: "nacos"
        - name: MYSQL_PASSWORD
          value: "nacos"
        volumeMounts:
        - name: nacos-mysql-storage
          mountPath: /var/lib/mysql
          subPath: nacos-mysql
          readOnly: false
      volumes:
      - name: nacos-mysql-storage
        persistentVolumeClaim:
          claimName: nacos-mysql-data
