apiVersion: apps/v1
kind: Deployment
metadata:
  name: canal-admin
  namespace: default
  labels:
    app: canal-admin
spec:
  replicas: 2
  selector:
    matchLabels:
      app: canal-admin
  template:
    metadata:
      labels:
        app: canal-admin
    spec:
      containers:
        - image: canal/canal-admin:v1.1.4
          name: canal-admin
          ports:
            - containerPort: 8089
              name: canal-admin
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 2000m
              memory: 2Gi
          volumeMounts:
            - mountPath: /home/canal/conf/application.yml
              subPath: application.yml
              name: canal-admin-conf
      volumes:
        - name: canal-admin-conf
          configMap:
            name: canal-conf
      securityContext:
        runAsUser: 0