---
apiVersion: v1
kind: Service
metadata:
  name: canal-admin-svc
  namespace: default
  labels:
    app: canal-admin-svc
spec:
  type: ClusterIP
  ports:
    - name: canal-admin-api
      port: 8089
      targetPort: 8089
  selector:
    app: canal-admin

