apiVersion: v1
kind: ConfigMap
metadata:
  name: canal-conf
  namespace: default
data:
  application.yml: |
    server.port: 8090
    spring.jackson.date-format: yyyy-MM-dd HH:mm:ss
    spring.jackson.time-zone: GMT+8
    spring.datasource.address: canal-mysql
    spring.datasource.database: ${CANAL_ADMIN_DATABASE}
    spring.datasource.username: ${CANAL_ADMIN_USER}
    spring.datasource.password: ${CANAL_ADMIN_PASSWORD}
    spring.datasource.driver-class-name: "com.mysql.jdbc.Driver"
    spring.datasource.url: "jdbc:mysql://${spring.datasource.address}/${spring.datasource.database}?useUnicode=true&characterEncoding=UTF-8&useSSL=false"
    canal.adminUser: ${CANAL_ADMIN_USER}
    canal.adminPasswd: ${CANAL_ADMIN_PASSWORD}

  canal.properties: |
    canal.register.ip=${HOSTNAME}
    canal.admin.manager=canal-admin:8089
    canal.admin.port=11110
    canal.admin.user=${CANAL_ADMIN_USER}
    canal.admin.passwd=${CANAL_ADMIN_PASSWORD}
    canal.admin.register.auto=true
    canal.admin.register.cluster=digit_canal
