---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: canal-mysql-data
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
  volumeMode: Filesystem

