apiVersion: apps/v1
kind: Deployment
metadata:
  name: canal-mysql
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: canal-mysql
  template:
    metadata:
      labels:
        app: canal-mysql
    spec:
      containers:
        - name: canal-mysql
          image: registry.cn-hangzhou.aliyuncs.com/zhlking/canal-mysql:v1.1.4-2
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: CANAL_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  key: Username
                  name: canal-user-passwd
            - name: CANAL_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: PassWord
                  name: canal-user-passwd
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: canal-mysql-data
              mountPath: /var/lib/mysql/
      volumes:
        - name: canal-mysql-data
          persistentVolumeClaim:
            claimName: canal-mysql-data