---
apiVersion: v1
kind: Service
metadata:
  name: canal-mysql
  namespace: default
  labels:
    name: canal-mysql
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    name: canal-mysql
  clusterIP: None