---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: canal-mysql-data
  namespace: default
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
