---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv1
  namespace: redis
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain


  volumeClaimTemplates:
    - persistentVolumeReclaimPolicy: Retain
      metadata:
        name: redis-data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: longhorn
        resources:
          requests:
            storage: 5Gi